use flightsbookingsystem;

INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Bucuresti", "Iasi", "2021-04-01", "09:00", "10:10")
INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Bucuresti", "Iasi", "2021-04-15", "12:00", "13:10")
INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Bucuresti", "Suceava", "2021-04-01", "08:00", "09:15")
INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Bucuresti", "Suceava", "2021-04-27", "15:20", "16:35")
INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Bucuresti", "Timisoara", "2021-04-03", "06:00", "07:05")
INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Bucuresti", "Timisoara", "2021-04-10", "11:30", "12:35")
INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Iasi", "Bucuresti", "2021-04-10", "12:30", "13:40")
INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Iasi", "Bucuresti", "2021-04-21", "10:15", "11:25")
INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Suceava", "Bucuresti", "2021-04-15", "07:20", "08:35")
INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Suceava", "Bucuresti", "2021-04-28", "15:20", "16:35")
INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Timisoara", "Bucuresti", "2021-04-17", "07:30", "08:35")
INSERT INTO flight(departurePlace, destination, date, departureTime, arrivalTime) VALUES ("Timisoara", "Bucuresti", "2021-04-30", "18:30", "19:35")


INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 1)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 1)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 1)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 1)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 1)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 1)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 1)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 1)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 1)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 1)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 1)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 1)

INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 2)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 2)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 2)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 2)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 2)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 2)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 2)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 2)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 2)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 2)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 2)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 2)

INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 3)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 3)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 3)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 3)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 3)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 3)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 3)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 3)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 3)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 3)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 3)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 3)

INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 4)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 4)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 4)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 4)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 4)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 4)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 4)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 4)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 4)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 4)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 4)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 4)

INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 5)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 5)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 5)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 5)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 5)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 5)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 5)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 5)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 5)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 5)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 5)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 5)

INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 6)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 6)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 6)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 6)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 6)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 6)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 6)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 6)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 6)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 6)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 6)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 6)

INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 7)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 7)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 7)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 7)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 7)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 7)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 7)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 7)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 7)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 7)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 7)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 7)

INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 8)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 8)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 8)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 8)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 8)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 8)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 8)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 8)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 8)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 8)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 8)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 8)

INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 9)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 9)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 9)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 9)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 9)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 9)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 9)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 9)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 9)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 9)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 9)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 9)

INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 10)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 10)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 10)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 10)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 10)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 10)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 10)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 10)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 10)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 10)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 10)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 10)

INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 11)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 11)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 11)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 11)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 11)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 11)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 11)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 11)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 11)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 11)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 11)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 11)

INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1A", false, 12)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1B", true, 12)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("1C", true, 12)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2A", false, 12)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2B", true, 12)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("2C", true, 12)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3A", false, 12)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3B", true, 12)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("3C", true, 12)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4A", true, 12)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4B", false, 12)
INSERT INTO flight_seats_treemap(seat_name, seat_available, flight_id) VALUES("4C", true, 12)

INSERT INTO ticket(price, flight_id) VALUES(35, 1)
INSERT INTO ticket(price, flight_id) VALUES(30, 2)
INSERT INTO ticket(price, flight_id) VALUES(35, 3)
INSERT INTO ticket(price, flight_id) VALUES(40, 4)
INSERT INTO ticket(price, flight_id) VALUES(32, 5)
INSERT INTO ticket(price, flight_id) VALUES(30, 6)
INSERT INTO ticket(price, flight_id) VALUES(40, 7)
INSERT INTO ticket(price, flight_id) VALUES(43, 8)
INSERT INTO ticket(price, flight_id) VALUES(45, 9)
INSERT INTO ticket(price, flight_id) VALUES(40, 10)
INSERT INTO ticket(price, flight_id) VALUES(35, 11)
INSERT INTO ticket(price, flight_id) VALUES(30, 12)
